# Generated by Django 5.2.5 on 2025-12-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infocad',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infocad',
            name='nome',
            field=models.TextField(max_length=200),
        ),
    ]
