# Generated by Django 5.2.8 on 2025-12-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_infocad_id_alter_infocad_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='infocad',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
